// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: streamingData/streamingData.proto

package streamingData

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_streamingData_streamingData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamingData_streamingData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_streamingData_streamingData_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        string                 `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Part          int32                  `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_streamingData_streamingData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamingData_streamingData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_streamingData_streamingData_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetBuffer() string {
	if x != nil {
		return x.Buffer
	}
	return ""
}

func (x *DataResponse) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

var File_streamingData_streamingData_proto protoreflect.FileDescriptor

const file_streamingData_streamingData_proto_rawDesc = "" +
	"\n" +
	"!streamingData/streamingData.proto\"\x1d\n" +
	"\vDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\fDataResponse\x12\x16\n" +
	"\x06buffer\x18\x01 \x01(\tR\x06buffer\x12\x12\n" +
	"\x04part\x18\x02 \x01(\x05R\x04part2G\n" +
	"\x10StreamingService\x123\n" +
	"\x10GetDataStreaming\x12\f.DataRequest\x1a\r.DataResponse\"\x000\x01BLZJgithub.com/Nikitha2404/server-side-streaming/protogen/golang/streamingDatab\x06proto3"

var (
	file_streamingData_streamingData_proto_rawDescOnce sync.Once
	file_streamingData_streamingData_proto_rawDescData []byte
)

func file_streamingData_streamingData_proto_rawDescGZIP() []byte {
	file_streamingData_streamingData_proto_rawDescOnce.Do(func() {
		file_streamingData_streamingData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamingData_streamingData_proto_rawDesc), len(file_streamingData_streamingData_proto_rawDesc)))
	})
	return file_streamingData_streamingData_proto_rawDescData
}

var file_streamingData_streamingData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamingData_streamingData_proto_goTypes = []any{
	(*DataRequest)(nil),  // 0: DataRequest
	(*DataResponse)(nil), // 1: DataResponse
}
var file_streamingData_streamingData_proto_depIdxs = []int32{
	0, // 0: StreamingService.GetDataStreaming:input_type -> DataRequest
	1, // 1: StreamingService.GetDataStreaming:output_type -> DataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamingData_streamingData_proto_init() }
func file_streamingData_streamingData_proto_init() {
	if File_streamingData_streamingData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamingData_streamingData_proto_rawDesc), len(file_streamingData_streamingData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streamingData_streamingData_proto_goTypes,
		DependencyIndexes: file_streamingData_streamingData_proto_depIdxs,
		MessageInfos:      file_streamingData_streamingData_proto_msgTypes,
	}.Build()
	File_streamingData_streamingData_proto = out.File
	file_streamingData_streamingData_proto_goTypes = nil
	file_streamingData_streamingData_proto_depIdxs = nil
}
